# Generated by Django 3.2.9 on 2021-11-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='movie_api_id',
        ),
    ]
